package com.adaptris.core.drools.helloworld

import com.adaptris.core.drools.helloworld.Message;

rule "Hello World"
    dialect "mvel"
  when
    m : Message( status == Message.HELLO, message : message )
  then
      modify ( m ) { message = "Goodbye cruel world",
                     status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
  when
    Message( status == Message.GOODBYE, message : message )
  then
    System.out.println( message );
end